/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fnl_project;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JTable;
/**
 *
 * @author Ali Computers
 */
public class admin_inter extends javax.swing.JFrame {

    //private String LoggedInUser;

    /**
     * Creates new form admin_inter
     */
    public admin_inter() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reset_btn = new javax.swing.JButton();
        view_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        deposite_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reset_btn.setBackground(new java.awt.Color(153, 204, 255));
        reset_btn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        reset_btn.setText("RESET PINS");
        reset_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 120, 30));

        view_btn.setBackground(new java.awt.Color(153, 204, 255));
        view_btn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        view_btn.setText("VIEW INFO");
        view_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });
        getContentPane().add(view_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 120, 30));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        deposite_btn.setBackground(new java.awt.Color(204, 204, 255));
        deposite_btn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        deposite_btn.setText("DEPOSITE");
        deposite_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deposite_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deposite_btnActionPerformed(evt);
            }
        });
        getContentPane().add(deposite_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 120, 30));

        delete_btn.setBackground(new java.awt.Color(153, 204, 255));
        delete_btn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        delete_btn.setText("DELETE ACC");
        delete_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnl_project/back1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deposite_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deposite_btnActionPerformed
        // TODO add your handling code here:
        new NewJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deposite_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed

        new delete_form().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_delete_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed

      new reset_form().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_reset_btnActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed

    String dbURL = "jdbc:mysql://localhost:3306/db_connect";
    String username = "root";
    String password = "";

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");

        try (Connection con = DriverManager.getConnection(dbURL, username, password)) {
            // Select all users from the database
            String selectSQL = "SELECT * FROM info";
            PreparedStatement pst = con.prepareStatement(selectSQL);
            ResultSet rs = pst.executeQuery();

            // Create a table model to store the data
            DefaultTableModel tableModel = new DefaultTableModel();
            JTable table = new JTable(tableModel);

            // Add columns to the table
            tableModel.addColumn("ID");
            tableModel.addColumn("Name");
            tableModel.addColumn("Balance");

            // Add rows to the table with user information
            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("Name");
                double balance = rs.getDouble("balance");
                tableModel.addRow(new Object[]{id, name, balance});
            }

            // Display the table in a scrollable pane
            JScrollPane scrollPane = new JScrollPane(table);
            JOptionPane.showMessageDialog(this, scrollPane);
        }
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_view_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_inter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton deposite_btn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables
}
