/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fnl_project;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author Ali Computers
 */
public class transfer extends javax.swing.JFrame {

    /**
     * Creates new form transfer
     */
     static String LoggedInUser;
     
    public transfer(String LoggedInUser) {
        initComponents();
        this.LoggedInUser=LoggedInUser;
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TRANSFER = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TRANSFER.setBackground(new java.awt.Color(102, 204, 255));
        TRANSFER.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        TRANSFER.setText("TRANSFER");
        TRANSFER.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TRANSFER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRANSFERActionPerformed(evt);
            }
        });
        getContentPane().add(TRANSFER, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 100, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 210, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 210, -1));

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setText("<---");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RECIPIENTS'S ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 20));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AMOUNT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, 20));

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRANSFER CASH");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnl_project/all int2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TRANSFERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRANSFERActionPerformed
        // TODO add your handling code here:
         int recipientID = Integer.parseInt(jTextField1.getText());
    double transferAmount = Double.parseDouble(jTextField2.getText());

    // Database connection details
    String dbURL = "jdbc:mysql://localhost:3306/db_connect";
    String username = "root";
    String password = "";

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");

        try (Connection con = DriverManager.getConnection(dbURL, username, password)) {
            // Check current balance for the sender
            String senderSelectSQL = "SELECT balance FROM info WHERE Name = ?";
            PreparedStatement senderPst = con.prepareStatement(senderSelectSQL);
            senderPst.setString(1, LoggedInUser);
            ResultSet senderRs = senderPst.executeQuery();
            if (senderRs.next()) {
                double senderCurrentBalance = senderRs.getDouble("balance");
                if (senderCurrentBalance >= transferAmount) {
                    // Deduct amount from sender's account
                    String senderUpdateSQL = "UPDATE info SET balance = ? WHERE Name = ?";
                    PreparedStatement senderUpdateStmt = con.prepareStatement(senderUpdateSQL);
                    senderUpdateStmt.setDouble(1, senderCurrentBalance - transferAmount);
                    senderUpdateStmt.setString(2, LoggedInUser);
                    int senderRowsAffected = senderUpdateStmt.executeUpdate();
                    if (senderRowsAffected > 0) {
                        // Add amount to recipient's account using recipient's ID
                        String recipientUpdateSQL = "UPDATE info SET balance = balance + ? WHERE id = ?";
                        PreparedStatement recipientUpdateStmt = con.prepareStatement(recipientUpdateSQL);
                        recipientUpdateStmt.setDouble(1, transferAmount);
                        recipientUpdateStmt.setInt(2, recipientID);
                        int recipientRowsAffected = recipientUpdateStmt.executeUpdate();
                        if (recipientRowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "Transfer successful.");
                        } else {
                            JOptionPane.showMessageDialog(this, "Failed to transfer funds to recipient.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to deduct funds from sender.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Insufficient balance in sender's account.");
                }
            } else {
                // Sender account not found
                JOptionPane.showMessageDialog(this, "Sender account not found.");
            }
        }
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_TRANSFERActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new user_inter(LoggedInUser).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer(LoggedInUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TRANSFER;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
