/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fnl_project;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author Ali Computers
 */
public class user_log extends javax.swing.JFrame {

    /**
     * Creates new form user_log
     */
   static String LoggedInUser;
    public user_log(String LoggedInUser) {
        initComponents();
        this.LoggedInUser=LoggedInUser;
        this.setResizable(false);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        user_textfield = new javax.swing.JTextField();
        user_passfield = new javax.swing.JPasswordField();
        lbl_admin_name = new javax.swing.JLabel();
        lbl_admin_pass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back_but = new javax.swing.JButton();
        login = new javax.swing.JButton();
        register_but = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(user_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 250, -1));
        getContentPane().add(user_passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 250, -1));

        lbl_admin_name.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lbl_admin_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_admin_name.setText("USERNAME");
        getContentPane().add(lbl_admin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 120, -1));

        lbl_admin_pass.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lbl_admin_pass.setForeground(new java.awt.Color(255, 255, 255));
        lbl_admin_pass.setText("PASSWORD");
        getContentPane().add(lbl_admin_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, 20));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, 80));

        back_but.setBackground(new java.awt.Color(153, 153, 255));
        back_but.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        back_but.setText("BACK");
        back_but.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_butActionPerformed(evt);
            }
        });
        getContentPane().add(back_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 30));

        login.setBackground(new java.awt.Color(51, 51, 255));
        login.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 100, 30));

        register_but.setBackground(new java.awt.Color(204, 0, 0));
        register_but.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        register_but.setForeground(new java.awt.Color(255, 255, 255));
        register_but.setText("REGISTER");
        register_but.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_butActionPerformed(evt);
            }
        });
        getContentPane().add(register_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fnl_project/LOGINYR22.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_butActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back_butActionPerformed

    private void register_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_butActionPerformed
        // TODO add your handling code here:
        
        new register_form(LoggedInUser).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_register_butActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

 try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String dbURL = "jdbc:mysql://localhost:3306/db_connect";
            String username = "root";
            String password = "";
            try (Connection con = DriverManager.getConnection(dbURL, username, password)) {
                String query = "SELECT * FROM info WHERE Name=? AND Pin=?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, user_textfield.getText());
                pst.setString(2, new String(user_passfield.getPassword()));
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    // Open the operations frame if login is successful
                    String LoggedInUser = rs.getString("Name"); // Assuming the column name is "Name"
                   new user_inter(LoggedInUser).setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid username or password.");
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database connection error: " + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }}
      /* try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String db= "jdbc:mysql://localhost:3306/db_connect";
    String username="root";
            String password="";
             // String username = user_textfield.getText();
             // String password = new String(user_passfield.getPassword());
            try (Connection con = DriverManager.getConnection(db,username, password)) {
                String query = "SELECT * FROM info WHERE Name=? AND Pin=?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, user_textfield.getText());
                pst.setString(2, user_passfield.getText());
                ResultSet rs =pst.executeQuery();
                if (rs.next()) {
                    new user_inter().setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid username or password.");
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(user_log.this, "Database connection error: " + ex.getMessage());
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(user_log.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_loginActionPerformed
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new user_log(LoggedInUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_but;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_admin_name;
    private javax.swing.JLabel lbl_admin_pass;
    private javax.swing.JButton login;
    private javax.swing.JButton register_but;
    private javax.swing.JPasswordField user_passfield;
    private javax.swing.JTextField user_textfield;
    // End of variables declaration//GEN-END:variables
}
